"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, Building2, Landmark, Pencil, PiggyBank, Plus, Trash2, WalletCards } from "lucide-react";
import { useState } from "react";
import { BottomSheet } from "@/components/ui/BottomSheet";
import { formatCurrency } from "@/lib/utils/format";
import type { FinancialItemKind, FinancialSnapshotItem } from "@/lib/db/financial-snapshot";

type Draft = { id?: string; kind: FinancialItemKind; name: string; institution: string; amount: string; dueDate: string; notes: string };
const empty: Draft = { kind: "account", name: "", institution: "", amount: "", dueDate: "", notes: "" };
const labels: Record<FinancialItemKind, string> = { account: "חשבון בנק", savings: "חיסכון", deposit: "פקדון", planned_expense: "הוצאה מתוכננת", reminder: "תזכורת" };

export function FinancialSnapshot() {
  const qc = useQueryClient(); const [draft, setDraft] = useState<Draft | null>(null); const [initial, setInitial] = useState<Draft | null>(null);
  const { data, isLoading } = useQuery({ queryKey: ["financial-snapshot"], queryFn: async () => { const res = await fetch("/api/financial-snapshot", { cache: "no-store" }); if (!res.ok) throw new Error("failed"); return res.json() as Promise<{ items: FinancialSnapshotItem[] }>; } });
  const save = useMutation({ mutationFn: async (value: Draft) => { const res = await fetch(value.id ? `/api/financial-snapshot/${value.id}` : "/api/financial-snapshot", { method: value.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...value, amount: value.amount === "" ? null : Number(value.amount), dueDate: value.dueDate || null }) }); const body = await res.json().catch(() => ({})) as { error?: string }; if (!res.ok) throw new Error(body.error || "השמירה נכשלה"); }, onSuccess: () => { setDraft(null); setInitial(null); qc.invalidateQueries({ queryKey: ["financial-snapshot"] }); } });
  const remove = useMutation({ mutationFn: async (id: string) => { const res = await fetch(`/api/financial-snapshot/${id}`, { method: "DELETE" }); if (!res.ok) throw new Error("מחיקה נכשלה"); }, onSuccess: () => qc.invalidateQueries({ queryKey: ["financial-snapshot"] }) });
  const items = data?.items ?? []; const balances = items.filter((i) => i.kind === "account" || i.kind === "savings" || i.kind === "deposit").reduce((sum, i) => sum + (i.amount ?? 0), 0); const planned = items.filter((i) => i.kind === "planned_expense").reduce((sum, i) => sum + (i.amount ?? 0), 0);
  const edit = (item: FinancialSnapshotItem) => { const next: Draft = { id: item.id, kind: item.kind, name: item.name, institution: item.institution ?? "", amount: item.amount === null ? "" : String(item.amount), dueDate: item.due_date ?? "", notes: item.notes ?? "" }; setDraft(next); setInitial(next); };
  return <div className="mx-auto max-w-5xl space-y-5 pb-24"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.16em] text-primary">תמונה פיננסית אישית</p><h1 className="mt-1 text-2xl font-black">המידע שחשוב לך</h1><p className="mt-1 text-sm text-on-surface-variant">נשמר בנפרד מהתנועות והתכנון החודשי.</p></div><button type="button" onClick={() => { setDraft(empty); setInitial(empty); }} className="m3-btn-primary flex min-h-12 items-center gap-2 px-5"><Plus className="h-5 w-5" />כרטיסייה חדשה</button></header>
    <section className="finance-hero grid gap-3 rounded-[28px] p-5 text-white sm:grid-cols-2"><Stat label="יתרות וחסכונות" value={balances} /><Stat label="הוצאות מתוכננות" value={planned} /></section>
    {isLoading ? <p className="text-center text-sm text-on-surface-variant">טוען את התמונה הפיננסית…</p> : <div className="grid gap-4 sm:grid-cols-2">{(["account", "savings", "deposit", "planned_expense", "reminder"] as FinancialItemKind[]).map((kind) => <Group key={kind} kind={kind} items={items.filter((item) => item.kind === kind)} onEdit={edit} onDelete={(item) => window.confirm(`למחוק את ${item.name}?`) && remove.mutate(item.id)} />)}</div>}
    {(save.isError || remove.isError) && <p role="alert" className="m3-error">{save.error?.message ?? "הפעולה נכשלה"}</p>}
    <BottomSheet open={Boolean(draft)} onClose={() => { setDraft(null); setInitial(null); }} title={draft?.id ? "עריכת כרטיסייה" : "כרטיסייה חדשה"} dirty={Boolean(draft && initial && JSON.stringify(draft) !== JSON.stringify(initial))} footer={draft ? <button type="button" disabled={!draft.name.trim() || save.isPending} onClick={() => save.mutate(draft)} className="m3-btn-primary min-h-[54px] w-full">{save.isPending ? "שומר…" : "שמירת הכרטיסייה"}</button> : undefined}>{draft && <Form draft={draft} setDraft={setDraft} />}</BottomSheet>
  </div>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-xs text-white/70">{label}</p><strong dir="ltr" className="mt-1 block text-2xl">{formatCurrency(value)}</strong></div>; }
function Group({ kind, items, onEdit, onDelete }: { kind: FinancialItemKind; items: FinancialSnapshotItem[]; onEdit: (item: FinancialSnapshotItem) => void; onDelete: (item: FinancialSnapshotItem) => void }) { const Icon = kind === "account" ? Landmark : kind === "savings" ? PiggyBank : kind === "deposit" ? Building2 : kind === "planned_expense" ? WalletCards : BellRing; return <section className="finance-panel !p-0 overflow-hidden"><div className="flex items-center gap-3 border-b border-outline-variant p-4"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary-container text-primary"><Icon className="h-5 w-5" /></div><h2 className="font-black">{labels[kind]}</h2></div><div className="divide-y divide-outline-variant">{items.map((item) => <article key={item.id} className="flex min-h-[66px] items-center gap-2 p-3"><button type="button" className="min-w-0 flex-1 text-start" onClick={() => onEdit(item)}><b className="block truncate text-sm">{item.name}</b><small className="block truncate text-on-surface-variant">{item.institution || item.due_date || item.notes || "ללא פרטים נוספים"}</small></button>{item.amount !== null && <strong dir="ltr" className="text-sm">{formatCurrency(item.amount)}</strong>}<button type="button" aria-label="עריכה" onClick={() => onEdit(item)} className="flex h-10 w-10 items-center justify-center rounded-xl text-primary"><Pencil className="h-4 w-4" /></button><button type="button" aria-label="מחיקה" onClick={() => onDelete(item)} className="flex h-10 w-10 items-center justify-center rounded-xl text-error"><Trash2 className="h-4 w-4" /></button></article>)}{!items.length && <p className="p-4 text-center text-xs text-on-surface-variant">אין עדיין פריטים</p>}</div></section>; }
function Form({ draft, setDraft }: { draft: Draft; setDraft: (value: Draft) => void }) { return <div className="grid gap-4"><label><span className="m3-label">סוג</span><select className="m3-input mt-1 w-full px-3 py-3" value={draft.kind} onChange={(e) => setDraft({ ...draft, kind: e.target.value as FinancialItemKind })}>{(Object.keys(labels) as FinancialItemKind[]).map((kind) => <option key={kind} value={kind}>{labels[kind]}</option>)}</select></label><label><span className="m3-label">שם</span><input autoFocus className="m3-input mt-1 w-full px-3 py-3" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder="למשל: חשבון עו״ש" /></label><label><span className="m3-label">בנק / גוף מנהל</span><input className="m3-input mt-1 w-full px-3 py-3" value={draft.institution} onChange={(e) => setDraft({ ...draft, institution: e.target.value })} /></label><div className="grid grid-cols-2 gap-3"><label><span className="m3-label">סכום</span><input type="number" inputMode="decimal" dir="ltr" className="m3-input mt-1 w-full px-3 py-3" value={draft.amount} onChange={(e) => setDraft({ ...draft, amount: e.target.value })} placeholder="אופציונלי" /></label><label><span className="m3-label">תאריך לתזכורת</span><input type="date" className="m3-input mt-1 w-full px-3 py-3" value={draft.dueDate} onChange={(e) => setDraft({ ...draft, dueDate: e.target.value })} /></label></div><label><span className="m3-label">הערה</span><textarea className="m3-input mt-1 min-h-24 w-full px-3 py-3" value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} /></label></div>; }
